name: uzum_bank
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get_it: ^7.2.0
  hive: ^2.2.3
  intl_phone_field: ^3.1.0
  path_provider: ^2.0.13
  alice: ^0.3.2
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/